### ISSUE TITLE
Addon Crashes after update `2020-02-18`

### ISSUE THREAD

**Issue by Cardosaum** [jakeprobst/anki-loadbalancer#12]
Hey!

I'm getting some errors after perform the update `2020-02-18`.
This is the traceback:

``` text
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons possibly involved: load balancer
```
``` python
Caught exception:
  File "aqt/webview.py", line 322, in handler
  File "aqt/reviewer.py", line 281, in _onAnswerButton
  File "aqt/reviewer.py", line 237, in _answerCard
  File "anki/sched.py", line 83, in answerCard
  File "anki/sched.py", line 527, in _answerLrnCard
  File "/home/matheus/.local/share/Anki2/addons21/1417170896/loadbalancer.py", line 163, in NEW_rescheduleAsRev
    card.ivl = NEW_adjRevIvl(self, card, card.ivl)
  File "/home/matheus/.local/share/Anki2/addons21/1417170896/loadbalancer.py", line 112, in NEW_adjRevIvl
    p(BeautifulSoup(card.render_output().question_text, "html.parser").getText())
<class 'AttributeError'>: 'Card' object has no attribute 'render_output'
```

I don't know which more information to provide,
so feel free to ask and I'll supply.

**Comment by RawToast** [comment]
`render_output` was added to the card type recently, I suggest upgrading to `2.1.20` I had the same issue on `2.1.15` and resolved it by upgrading. 

Likewise, if you upgrade to `2.1.20` with an older plugin, it will crash as `_getQA` was removed.

**Comment by Cardosaum** [comment]
@RawToast 

Thanks for explaining!

I tried upgrade to `2.1.10`, but several other addons are still incompatible with this version.

Is there some way to downgrade `loadbalancer` to the previous version?

**Comment by RawToast** [comment]
I would manually change the line of code. `Add-ons` -> Select `load balancer` -> `view files`

Open `loadbalancer.py` with notepad/textedit/vscode. Do a find/replace for `render_output().question_text` replacing it with `_getQA()['q']`. It should only appear once 😸 

Restart Anki and cross your fingers 😆  That's the only change in the recent update, so it should solve the issue -- it did for me before I upgraded.

**Comment by Cardosaum** [comment]
Thank you so much, @RawToast !
It's working like a charm now.
