### ISSUE TITLE
Latest update broke older versions

### ISSUE THREAD

**Issue by dae** [jakeprobst/anki-loadbalancer#17]
A number of users on older Anki versions have reported being unable to start the program after the latest update. I recommend you upload the older source, set a maximum version number, and then you can share a difference branch intended to work with 2.1.28+

Edit: I have set it to .28 only for now, to prevent it from breaking things for more users.

**Comment by dae** [comment]
For users linked here: you can fix the problem either by updating to the latest Anki version, or by starting Anki while holding down the shift key, then disabling the load balancer add-on in the add-on preferences.

**Comment by jakeprobst** [comment]
updated the page to have both versions. I wasn't aware of this functionality thanks.
