### ISSUE TITLE
Anki 2.1 Caught Exception

### ISSUE THREAD

**Issue by DrewSSP** [jakeprobst/anki-loadbalancer#8]
Answering a question creates an error with the following message:

**Comment by DrewSSP** [comment]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.3 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt/reviewer.py", line 276, in onEnterKey
  File "aqt/reviewer.py", line 236, in _answerCard
  File "anki/sched.py", line 87, in answerCard
  File "anki/sched.py", line 808, in _answerRevCard
  File "anki/sched.py", line 854, in _rescheduleRev
  File "anki/sched.py", line 931, in _updateRevIvl
  File "/Users/drewpilcher/Library/Application Support/Anki2/addons21/1417170896/loadbalancer.py", line 112, in NEW_adjRevIvl
    p(BeautifulSoup(card._getQA()['q'], "lxml").getText())
  File "bs4/__init__.py", line 165, in __init__
<class 'bs4.FeatureNotFound'>: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by jakeprobst** [comment]
I can't replicate this, can anyone else?

**Comment by jakeprobst** [comment]
Also you're free to open loadbalancer.py and delete that line, it is purely for debugging.

**Comment by hsteve020** [comment]
I had not run into that error with load balancer

**Comment by DrewSSP** [comment]
I commented out line 112 in loadbalancer.py as suggested and the error message disappeared.

**Comment by jakeprobst** [comment]
try grabbing the latest version see if it fixes it

**Comment by DrewSSP** [comment]
I update the add-on and have been using Load Balancer uninhibited for 20 minutes. The issue is fixed! Thanks for that.

**Comment by jakeprobst** [comment]
awesome
